services:
  - type: web
    name: backstock-email-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_KEY_WILL_BE_SET_IN_RENDER
